<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameter 'person_id', 'surname' and 'name' from GET Request
// Btw. you can see the parameters in the URL if they are set
$Studio_ID = '';
if (isset($_GET['Studio_ID'])) {
    $Studio_ID  = $_GET['Studio_ID'];
}

$F_Name = '';
if (isset($_GET['F_Name'])) {
    $F_Name = $_GET['F_Name'];
}

$Ort = '';
if (isset($_GET['Ort'])) {
    $Ort = $_GET['Ort'];
}

$Platz = '';
if (isset($_GET['Platz'])) {
    $Platz = $_GET['Platz'];
}


$Strasse = '';
if (isset($_GET['Strasse'])) {
    $Strasse = $_GET['Strasse'];
}


//Fetch data from database
$studio_array = $database->selectAllFitnessstudio($Studio_ID, $F_Name, $Ort, $Platz, $Strasse);
?>

<html lang="en">
<head>
    <title>DBS Tutorial</title>
</head>

<body>
<br>
<h1>My First PHP Project</h1>

<!-- Add Person -->
<h2>Add Fitnessstudio: </h2>
<form method="post" action="addPerson.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <div>
        <label for="new_ID">ID:</label>
        <input id="new_ID" name="Studio_ID" type="number" min="1">
    </div>
    <br>

    <!-- Name textbox -->
    <div>
        <label for="new_F_Name">Name:</label>
        <input id="new_F_Name" name="F_Name" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_Ort">Ort:</label>
        <input id="new_Ort" name="Ort" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="new_Platz">Platz:</label>
        <input id="new_Platz" name="Platz" type="number">
    </div>
    <br>

    <div>
        <label for="new_Strasse">Strasse:</label>
        <input id="new_Strasse" name="Strasse" type="text" maxlength="20">
    </div>
    <br>


    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Fitnessstudio
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Fitnessstudio: </h2>
<form method="post" action="delPerson.php">
    <!-- ID textbox -->
    <div>
        <label for="Studio_ID">ID:</label>
        <input id="Studio_ID" name="Studio_ID" type="number" min="1">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Fitnessstudio
        </button>
    </div>
</form>
<br>
<hr>

<!-- Update Person -->
<h2


<!-- Search form -->
<h2>Fitnessstudio Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="Studio_ID">ID:</label>
        <input id="Studio_ID" name="Studio_ID" type="number" value='<?php echo $Studio_ID; ?>' min="1">
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="F_Name">Name:</label>
        <input id="F_Name" name="F_Name" type="text" class="form-control input-md" value='<?php echo $F_Name; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Fitnessstudio Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
    </tr>
    <?php foreach ($studio_array as $Fitnessstudio) : ?>
        <tr>
            <td><?php echo $Fitnessstudio['STUDIO_ID']; ?>  </td>
            <td><?php echo $Fitnessstudio['F_NAME']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

</body>
</html>