<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameter 'person_id', 'surname' and 'name' from GET Request
// Btw. you can see the parameters in the URL if they are set

$Studio_ID = '';
if (isset($_GET['Studio_ID'])) {
    $Studio_ID  = $_GET['Studio_ID'];
}

$F_Name = '';
if (isset($_GET['F_Name'])) {
    $F_Name = $_GET['F_Name'];
}

$Ort = '';
if (isset($_GET['Ort'])) {
    $Ort = $_GET['Ort'];
}

$Platz = '';
if (isset($_GET['Platz'])) {
    $Platz = $_GET['Platz'];
}


$Strasse = '';
if (isset($_GET['Strasse'])) {
    $Strasse = $_GET['Strasse'];
}


//Fetch data from database
$studio_array = $database->selectAllFitnessstudio($Studio_ID, $F_Name, $Ort, $Platz, $Strasse);
?>

<html lang="en">
<head>
    <title>Fitnessstudio</title>
</head>

<body>
<br>
<h1>My First PHP Project</h1>

<!-- Add Person -->
<h2>Add Fitnessstudio: </h2>
<form method="post" action="addPerson.php">
    <!-- ID is not needed, because its autogenerated by the database -->

    <div>
        <label for="new_ID">ID:</label>
        <input id="new_ID" name="Studio_ID" type="number" min="1">
    </div>
    <br>

    <!-- Name textbox -->
    <div>
        <label for="new_F_Name">Name:</label>
        <input id="new_F_Name" name="F_Name" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_Ort">Ort:</label>
        <input id="new_Ort" name="Ort" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="new_Platz">Platz:</label>
        <input id="new_Platz" name="Platz" type="number">
    </div>
    <br>

    <div>
        <label for="new_Strasse">Strasse:</label>
        <input id="new_Strasse" name="Strasse" type="text" maxlength="20">
    </div>
    <br>


    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Fitnessstudio
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Delete Fitnessstudio: </h2>
<form method="post" action="delPerson.php">
    <!-- ID textbox -->
    <div>
        <label for="Studio_ID">ID:</label>
        <input id="Studio_ID" name="Studio_ID" type="number" min="1">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Fitnessstudio
        </button>
    </div>
</form>
<br>
<hr>

<!-- Update Person -->
<h2>Update Fitnessstudio: </h2>
<form method="post" action="updatePerson.php">
    <!-- ID textbox -->
    <div>
        <label for="Studio_IDs">ID:</label>
        <input id="Studio_IDs" name="Studio_ID" type="number" min="1">
    </div>
    <br>
    <h3>Update Values: </h3>
    <!-- Name textbox -->
    <div>
        <label for="new_Studio_IDs">ID:</label>
        <input id="new_Studio_IDs" name ="Studio_IDs" type="number" min="1">
    </div>
    <br>
    <div>
        <label for="new_F_Names">Name:</label>
        <input id="new_F_Names" name="F_Name" type="text" maxlength="20">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_Orts">Ort:</label>
        <input id="new_Orts" name="Ort" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="new_Platzs">Platz:</label>
        <input id="new_Platzs" name="Platz" type="number">
    </div>
    <br>

    <div>
        <label for="new_Strasses">Strasse:</label>
        <input id="new_Strasses" name="Strasse" type="text" maxlength="20">
    </div>
    <br>
    <div>
        <button id ='update' type='submit'>
           Update
        </button>
    </div>
</form>
<br>
<hr>



<!-- Search form -->
<h2>Fitnessstudio Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="Studio_ID">ID:</label>
        <input id="Studio_ID" name="Studio_ID" type="number" value='<?php echo $Studio_ID; ?>' min="1">
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="F_Name">Name:</label>
        <input id="F_Name" name="F_Name" type="text" class="form-control input-md" value='<?php echo $F_Name; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Fitnessstudio Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Ort</th>
        <th>Platz</th>
        <th>Strasse</th>

    </tr>
    <?php foreach ($studio_array as $Fitnessstudio) : ?>
        <tr>
            <td><?php echo $Fitnessstudio['STUDIO_ID']; ?>  </td>
            <td><?php echo $Fitnessstudio['F_NAME']; ?>  </td>
            <td><?php echo $Fitnessstudio['ORT']; ?>  </td>
            <td><?php echo $Fitnessstudio['PLATZ']; ?>  </td>
            <td><?php echo $Fitnessstudio['STRASSE']; ?>  </td>

        </tr>
    <?php endforeach; ?>
</table>

<br>
<hr>

<h2>Add Mitarbeiter: </h2>
<form method="post" action="addMitarbeiter.php">

    <div>
        <label for="new_ID">ID:</label>
        <input id="new_ID" name="Mitarbeiter_ID" type="number">
    </div>
    <br>

    <div>
        <label for="new_F_ID">Studio-ID:</label>
        <input id="new_F_ID" name="Studio_ID" type="number" min="1">
    </div>
    <br>

    <div>
        <label for="new_Vorname">Vorname:</label>
        <input id="new_Vorname" name="Vorname" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="new_Nachname">Nachname:</label>
        <input id="new_Nachname" name="Nachname" type="text" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Mitarbeiter
        </button>
    </div>
</form>
<br>
<hr>


<!-- Delete Person -->
<h2>Delete Mitarbeiter: </h2>
<form method="post" action="delMitarbeiter.php">
    <div>
        <label for="newM_ID">ID:</label>
        <input id="newM_ID" name="Mitarbeiter_ID" type="number" min="1">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Delete Mitarbeiter
        </button>
    </div>
</form>
<br>
<hr>



<h2>Update Mitarbeiter: </h2>
<form method="post" action="updateMitarbeiter.php">
    <!-- ID textbox -->
    <div>
        <label for="Mitarbeiter_IDs">ID:</label>
        <input id="Mitarbeiter_IDs" name="Mitarbeiter_ID" type="number">
    </div>
    <br>
    <h3>Update Values: </h3>
    <!-- Name textbox -->
    <div>
        <label for="new_Mitarbeiter_IDs">ID:</label>
        <input id="new_Mitarbeiter_IDs" name ="Mitarbeiter_IDs" type="number">
    </div>
    <br>
    <div>
        <label for="new_Studio_IDs_Names">Studio-ID:</label>
        <input id="new_Studio_IDs_Names" name="Studio_ID"  type="number">
    </div>
    <br>

    <!-- Surname textbox -->
    <div>
        <label for="new_Vorname">Vorname:</label>
        <input id="new_Nachname" name="Vorname" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="new_Nachname">Nachname:</label>
        <input id="new_Nachname" name="Nachname" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <button id ='update' type='submit'>
            Update
        </button>
    </div>
</form>
<br>
<hr>

<?php
$Mitarbeiter_ID = '';
if (isset($_GET['Mitarbeiter_ID'])) {
    $Mitarbeiter_ID  = $_GET['Mitarbeiter_ID'];
}

$Studio_ID= '';
if (isset($_GET['Studio_ID'])) {
    $Studio_ID = $_GET['Studio_ID'];
}

$Vorname = '';
if (isset($_GET['Vorname'])) {
    $Vorname = $_GET['Vorname'];
}

$Nachname = '';
if (isset($_GET['Nachname'])) {
    $Nachname = $_GET['Nachname'];
}


//Fetch data from database
$studio_array = $database->selectAllMitarbeiter($Mitarbeiter_ID, $Studio_ID, $Vorname, $Nachname);
?>

<h2>Mitarbeiter Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="Mitarbeiter_ID">ID:</label>
        <input id="Mitarbeiter_ID" name="Mitarbeiter_ID" type="number" value='<?php echo $Mitarbeiter_ID; ?>'>
    </div>
    <br>

    <div>
        <label for="V_name">Vorname:</label>
        <input id="V_name" name="Vorname" type ="text" class="form-control input-md" value='<?php echo $Vorname; ?>'
               maxlength="20">
    </div>
    <br>

    <div>
        <label for="N_name">Nachname:</label>
        <input id="N_name" name="Nachname" type="text" class="form-control input-md" value='<?php echo $F_Name; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit_2' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Mitarbeiter Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Studio-ID</th>
        <th>Vorname</th>
        <th>Nachname</th>

    </tr>
    <?php foreach ($studio_array as $Mitarbeiter) : ?>
        <tr>
            <td><?php echo $Mitarbeiter['MITARBEITER_ID']; ?>  </td>
            <td><?php echo $Mitarbeiter['STUDIO_ID']; ?>  </td>
            <td><?php echo $Mitarbeiter['VORNAME']; ?>  </td>
            <td><?php echo $Mitarbeiter['NACHNAME']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

<br>
<hr>

<h2>Add Personal Trainer: </h2>
<form method="post" action="addPersonalTrainer.php">

    <div>
        <label for="P_ID">ID:</label>
        <input id="P_ID" name="Mitarbeiter_ID" type="number">
    </div>
    <br>

    <div>
        <label for="Geschlecht">Geschlecht (Male/Female):</label>
        <input id="Geschlecht" name="Geschlecht" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="Sprachkenntnisse">Sprachkenntnisse:</label>
        <input id="Sprachkenntnisse" name="Sprachkenntnisse" type="text" maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Add Personal Trainer
        </button>
    </div>
</form>
<br>
<hr>

<h2>Update Personal Trainer: </h2>
<form method="post" action="updatePersonalTrainer.php">
    <div>
        <label for="Personal_IDs">ID:</label>
        <input id="Personal_IDs" name="Mitarbeiter_ID" type="number">
    </div>
    <br>
    <h3>Update Values: </h3>
    <div>
        <label for="new_Personal_IDs">ID:</label>
        <input id="new_Personal_IDs" name ="Mitarbeiter_IDs" type="number">
    </div>
    <br>
    <div>
        <label for="Personal_G">Geschlecht:</label>
        <input id="Personal_G" name="Geschlecht"  type="text" maxlength="20">
    </div>
    <br>

    <div>
        <label for="Personal_S">Sprachkenntnisse:</label>
        <input id="Personal_S" name="Sprachkenntnisse" type="text" maxlength="20">
    </div>
    <br>

    <div>
        <button id ='update_3' type='submit'>
            Update
        </button>
    </div>
</form>
<br>
<hr>

<?php
$Mitarbeiter_ID = '';
if (isset($_GET['Mitarbeiter_ID'])) {
$Mitarbeiter_ID  = $_GET['Mitarbeiter_ID'];
}

$Geschlecht= '';
if (isset($_GET['Geschlecht'])) {
$Geschlecht = $_GET['Geschlecht'];
}

$Sprachkenntnisse= '';
if (isset($_GET['Sprachkenntnisse'])) {
    $Sprachkenntnisse = $_GET['Sprachkenntnisse'];
}


//Fetch data from database
$studio_array = $database->selectAllPersonalTrainer($Mitarbeiter_ID, $Geschlecht, $Sprachkenntnisse);
?>

<h2>Personal Trainer Search:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="Mitarbeiter_ID">ID:</label>
        <input id="Mitarbeiter_ID" name="Mitarbeiter_ID" type="number" value='<?php echo $Mitarbeiter_ID; ?>'>
    </div>
    <br>

    <div>
        <label for="P_G">Geschlecht:</label>
        <input id="P_G" name="Geschlecht" type ="text" class="form-control input-md" value='<?php echo $Geschlecht; ?>'
               maxlength="20">
    </div>
    <br>

    <div>
        <label for="P_S">Sprachkenntnisse:</label>
        <input id="P_S" name="Sprachkenntnisse" type="text" class="form-control input-md" value='<?php echo $Sprachkenntnisse; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit_4' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Personal Trainer Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Geschlecht</th>
        <th>Sprachkenntnisse</th>

    </tr>
    <?php foreach ($studio_array as $Personal_Trainer) : ?>
        <tr>
            <td><?php echo $Personal_Trainer['MITARBEITER_ID']; ?>  </td>
            <td><?php echo $Personal_Trainer['GESCHLECHT']; ?>  </td>
            <td><?php echo $Personal_Trainer['SPRACHKENNTNISSE']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

<br>
<hr>





</body>
</html>